name: markdown2pdf
on: push
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: juliangruber/read-file-action@v1
        id: readREADME
        with:
          path: ./README.md
      - uses: octokit/request-action@v2.x
        id: mdconv
        env:
          GITHUB_TOKEN: |
          "${{ secrets.GITHUB_TOKEN }}"
        with:
          route: POST /markdown
          text: "${{ toJSON(steps.readREADME.outputs.content) }}"
          mode: "gfm"
          context: "maxwellpollack/cv"
      - run: "echo ${{ steps.mdconv.outputs.data }}"
