name: markdown2pdf
on: push
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up Python 3.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install grip
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - run: grip --export
      - run: sudo apt-get install chromium-browser
      - run: chromium-browser --headless --disable-gpu --run-all-compositor-stages-before-draw --print-to-pdf=README.pdf README.html
      - name: Commit files
        run: |
          git config --local user.email "mail@maxis.cool"
          git config --local user.name "Max Pollack"
          git add README.pdf
          git commit -m "Update PDF"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
